#!/usr/bin/env nextflow
/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    FlorPio/gatk-cnv-pon
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Nextflow pipeline to create a GATK Panel of Normals (PON)
    for somatic CNV analysis.

    Input:  Samplesheet with normal sample BAMs
    Output: HDF5 Panel of Normals file

    Steps:
      1. PreprocessIntervals (once)
      2. CollectReadCounts (per sample)
      3. CreateReadCountPanelOfNormals (merge all)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

nextflow.enable.dsl = 2

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    IMPORT WORKFLOWS
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

include { CREATE_PON } from './workflows/create-pon'

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    NAMED WORKFLOW FOR PIPELINE
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

workflow {

    // Parse samplesheet: sample,bam,counts
    //   - 'bam'    -> sample needs CollectReadCounts
    //   - 'counts' -> HDF5 already generated by another pipeline; skip CollectReadCounts
    //   Exactly one of the two must be set per row.
    ch_parsed = Channel
        .fromPath(params.input, checkIfExists: true)
        .splitCsv(header: true)
        .map { row ->
            def meta    = [id: row.sample]
            def bam_raw = row.bam?.trim()
            def cnt_raw = row.counts?.trim()
            if (!bam_raw && !cnt_raw) {
                exit 1, "Samplesheet row '${row.sample}' has neither 'bam' nor 'counts' set"
            }
            [ meta, bam_raw, cnt_raw ]
        }
        .branch { meta, bam_raw, cnt_raw ->
            with_counts: cnt_raw
            with_bam:    bam_raw
        }

    ch_bams = ch_parsed.with_bam.map { meta, bam_raw, cnt_raw ->
        def bam = file(bam_raw, checkIfExists: true)
        def bai = file("${bam_raw}.bai", checkIfExists: false)
        [ meta, bam, bai ]
    }

    ch_counts = ch_parsed.with_counts.map { meta, bam_raw, cnt_raw ->
        def cnt = file(cnt_raw, checkIfExists: true)
        [ meta, cnt ]
    }

    CREATE_PON(ch_bams, ch_counts)
}